const actions = {
    ZOOM_IN:'ZOOM_IN',
    ZOOM_OUT:'ZOOM_OUT',
    MOUSE_DOWN:'MOUSE_DOWN',
    MOUSE_UP:'MOUSE_UP',
    MOUSE_MOVE:'MOUSE_MOVE',
    MOUSE_LEAVE:'MOUSE_LEAVE',
    FULL_SCREEN:'FULL_SCREEN',
    INIT_SCREEN:'INIT_SCREEN'
}
export default actions;